### ISSUE TITLE
Show Icon does not show the content of the Password field.

### ISSUE THREAD

**Issue by Niranjan2054** [maheshmnj/passwordfield-flutter-package#1]

**Comment by maheshj01** [comment]
Thank you for creating the first issue on this repo,I really appreciate your effort in taking time to create the issue,can you please elaborate the issue in detail this will help me in fixing it.

**Comment by maheshj01** [comment]
Its built as the show password Icon works when it gains focus meaning when the touch is in focus with the icon the password is visible and when you remove the focus it gets hidden.So I don't believe its a bug/issue. If you still feel its an issue please revert back and I will be happy to reopen this issue.
