### ISSUE TITLE
When i turn on caps lock on keyboard, delete key doesn't work

### ISSUE THREAD

**Issue by dinhtran16** [maheshmnj/passwordfield-flutter-package#12]

**Comment by maheshj01** [comment]
Hey @TranVanDinh235, Thanks for filing the issue. Please share the output of `flutter doctor -v` and the version of `passwordField` you are having issues with along with error or exception logs(if any). I highly suspect this to be a framework issue. 

Thanks.

**Comment by dinhtran16** [comment]
I use passwordField latest version, 1.0.1 and I don't see any error or exception logs
<img width="684" alt="Screen Shot 2021-09-25 at 08 30 26" src="https://user-images.githubusercontent.com/35059033/134753471-e07e9e84-f027-4847-849c-bf6eba66ae74.png">
.

**Comment by maheshj01** [comment]
I couldn't reproduce it, Could you please try upgrading to the latest stable version `2.5.1` by running  `flutter upgrade`?

Thanks.
