### ISSUE TITLE
errorMessage field too short

### ISSUE THREAD

**Issue by marcusaureliusbrutus** [maheshmnj/passwordfield-flutter-package#2]
Hi,

Just wanted to say that I genuinely appreciate this package.  

Regarding the errorMessage, it is critical for ordinary people entering their password to be advised on what should be included.  I was hoping to show the below in the errorMessage field but the length is too long and is only partially shown by errorMessage.  Is there a way to adjust the errorMessage field size to allow the entire text message below to appear?  Thanks in advance.

"Password should be 8 characters long with at least 1 Uppercase letter, 1 lowercase letter, 1 special character eg. . * @ # \$, and 1 number."

**Comment by maheshj01** [comment]
Thanks for the issue @marcusaureliusbrutus yes that's possible we simply need to add a new  property that inputs to the errorMaxLines property of the original TextField ,I will update here about the progress

**Comment by maheshj01** [comment]
Hello @marcusaureliusbrutus I have updated the package [passwordfield 0.0.7 is here](https://pub.dev/packages/passwordfield#-changelog-tab-)  with two new feature ```errorStyle``` and ```errorMaxLines```

<img src="https://user-images.githubusercontent.com/31410839/86485236-dc1e0680-bd75-11ea-91eb-5343afff0d5b.png" width="300">


I hope this resolves your issue I will be closing this issue for now assuming its resolved,feel free to reopen if you think it's not.
