### ISSUE TITLE
hintText Property is not working

### ISSUE THREAD

**Issue by Shalabyer** [maheshmnj/passwordfield-flutter-package#3]
hintText Property is not working, I tried to assign it but it just stays the same as the default which is 'Password'.

**Comment by maheshj01** [comment]
This issue seems to be fixed by @iamriajul , I will be closing this issue for now,Feel free to open up new issues pointing out bugs and enhancement requests.

**Comment by iamriajul** [comment]
New version need to be released on pub with my changes from pull request. @maheshmnj

**Comment by maheshj01** [comment]
Yeah sure,I will do that soon

**Comment by maheshj01** [comment]
@iamriajul the new version is published as (https://pub.dev/packages/passwordfield)[0.0.81]
