### ISSUE TITLE
Set Input Label

### ISSUE THREAD

**Issue by johnwargo** [maheshmnj/passwordfield-flutter-package#6]
In one of the example screen shots, you show a password input field with a label (Password) but none of the sample code shows how to set that. 

Whenever I try to set `hintText`, one of the assertions fires:

```text
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building EspTouch(dirty, state: _EspTouch#b5697):
'package:passwordfield/passwordfield.dart': Failed assertion: line 33 pos 16: 'hasFloatingPlaceholder == true && hintText == ''': is not true.

The relevant error-causing widget was: 
  EspTouch file:///D:/dev/fumbly-diddle/busy/busy-flutter/lib/pages/settings.dart:71:26
When the exception was thrown, this was the stack: 
#2      new PasswordField (package:passwordfield/passwordfield.dart:33:16)
#3      _EspTouch.build (package:busystatus/pages/esptouch.dart:345:11)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 4 of 719 libraries in 1,888ms.
```

I've tried several permutations (with and without setting `hasFloatingPlaceholder` and can't seem to get around this error. Can you help me?

**Comment by maheshj01** [comment]
Thanks for pointing out the issue, I have corrected it and released the [new version](https://pub.dev/packages/passwordfield/changelog)
please check for the updated package [passwordfield: ^0.0.82](https://pub.dev/packages/passwordfield)
I hope the source code documentation should be easy to understand

coming to your question
password field supports two types of hint and only 1 works at a time
- hintText : works when hasFloatingPlaceholder = false
- floatingText: works when hasFloatingplaceholder =true

I hope this answers your question and assume this to be resolved,I will be closing this issue for now feel free to reply back if you think this is not fixed I will reopen it or create a new issue if required
