### ISSUE TITLE
obscure text toggle 

### ISSUE THREAD

**Issue by tanmoy27112000** [maheshmnj/passwordfield-flutter-package#7]
Please add toggle to turn on obscure text so that we can use it for email field also.

**Comment by maheshj01** [comment]
Well Password field widget is built only for password fields you can always use the built in flutter text field for emails field and customize it the way you want. may I know what stops you from using the built in textfield for your email field? let me know if I could help

**Comment by maheshj01** [comment]
Closing this issue, since the feature request does not meet the goal why this widget is built feel free to create another issue if you think this widget is broken or requires modification or for a relevant feature request
