### ISSUE TITLE
please make a similar extension that we can use for emails and other feilds please 

### ISSUE THREAD

**Issue by fisforfaheem** [maheshmnj/passwordfield-flutter-package#9]

**Comment by maheshj01** [comment]
@fisforfaheem could you please tell whats the difficulty with the existing textfield to use it as a emailfield?

**Comment by fisforfaheem** [comment]
I meant you should make a pub.deb extension for other form fields. This one
is specific for password only as I am a beginner, I don't know how to use
it for other form fields too, nor their is there a tutorial.  you can make
a big package that can add all this



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
08/01/21,
05:45:13 PM

**Comment by maheshj01** [comment]
@fisforfaheem I don't think it would be appropriate to make a package for your use case. What I would suggest is you should create a custom text field widget as per the needs of your project and use it. It is pretty straightforward to do it. You can also look at the source code of this package on how to make one. And in case you need help feel free to drop your textfield requirement and I could help you build it.
Thanks

**Comment by maheshj01** [comment]
Closing this issue as invalid feel free to comment here, if you have any questions or need clarifications

**Comment by fisforfaheem** [comment]
Thank You so much :). Currently everything is working using text form field
validator if i got into any issue would surely contact you/ Thanks again



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
08/02/21,
02:27:52 PM
